version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false  # set true later if you want strict builds

conda:
  environment: docs/environment.yml

# Install your package from the working tree (uses pyproject.toml)
python:
  install:
    - method: pip
      path: .

formats:
  - htmlzip
  - pdf
  - epub