# .readthedocs.yml
# Read the Docs configuration file
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  # Optional: fetch submodules if you use them
  # jobs:
  #   post_checkout:
  #     - git submodule update --init --recursive

# Where your Sphinx conf.py lives
sphinx:
  configuration: docs/source/conf.py
  # Turn this on if you want builds to fail on Sphinx warnings
  fail_on_warning: false

# Produce downloadable artifacts (optional)
formats:
  - htmlzip
  - pdf
  - epub

# Use your conda environment for the build
conda:
  environment: installation/environment.yml

# Also pip-install the project so autodoc can import tirank (editable mode).
python:
  install:
    - method: pip
      path: .

# If you’d rather keep Sphinx/theme/extensions out of your Conda env,
# add a docs requirements file and uncomment the block below, then
# list things like sphinx, sphinx-rtd-theme, recommonmark/myst-parser, etc.
#  install:
#    - requirements: docs/requirements.txt
#    - method: pip
#      path: .
