version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

conda:
  environment: docs/environment.yml

# Optional: if you prefer pip-only instead of conda, you could drop the conda block
# and replace with:
# python:
#   install:
#     - method: pip
#       path: .
#     - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf
  - epub
