name: tirank-docs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - sphinx
  - myst-parser          # MyST for your .md files
  - sphinx-rtd-theme
  - sphinx-autodoc-typehints
  - numpy                # light/core dep that helps with imports and type hints
